# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ fetchurl }:

self: super: {
  "google-cloud-aiplatform" = super.buildPythonPackage rec {
    pname = "google-cloud-aiplatform";
    version = "1.108.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/09/403d8bddacb33ec67af5a981d6166f391a9c2a2cf163c2a6742bdf958966/google_cloud_aiplatform-1.108.0-py2.py3-none-any.whl";
      sha256 = "19hv8cyjv891szpc7s89j05f384i4cbibj5dsnhy8kvh1nzc6090";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."docstring-parser"
      self."google-api-core"
      self."google-auth"
      self."google-cloud-bigquery"
      self."google-cloud-resource-manager"
      self."google-cloud-storage"
      self."google-genai"
      self."packaging"
      self."proto-plus"
      self."protobuf"
      self."pydantic"
      self."shapely"
      self."typing-extensions"
    ];
  };
}
