#!/usr/bin/env bash
# ── Flemma Profiling Harness ─────────────────────────────────────
#
# Measures per-keystroke performance of .chat buffers by driving edits
# in a real Neovim instance via tmux. Compares a .chat buffer with
# Flemma loaded against a .md baseline (treesitter only, no Flemma).
#
# Prerequisites:
#   - tmux running (the harness creates background windows)
#   - nvim-treesitter installed (discovered automatically)
#   - Flemma loadable from the repo working directory
#
# Usage:
#   bash contrib/profile/run.sh              # uses bundled fixture
#   bash contrib/profile/run.sh path/to.chat # uses custom file
#
# The bundled fixture is generated by generate-fixture.lua. If missing,
# run:  nvim --headless --noplugin -u NONE --cmd 'set rtp^=.' \
#         -l contrib/profile/generate-fixture.lua
#
# Results are written to .profile/<timestamp>/ (gitignored).

set -euo pipefail

command -v tmux >/dev/null 2>&1 || {
  echo "ERROR: tmux is required but not found"
  exit 1
}
tmux has-session 2>/dev/null || {
  echo "ERROR: no tmux session found — start tmux first"
  exit 1
}
command -v nvim >/dev/null 2>&1 || {
  echo "ERROR: nvim is required but not found"
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
INIT_LUA="$SCRIPT_DIR/init.lua"
INSTRUMENT="$SCRIPT_DIR/instrument.lua"
FIXTURE="$SCRIPT_DIR/fixture.chat"

# ── Resolve input file ───────────────────────────────────────────
SOURCE_CHAT="${1:-$FIXTURE}"
if [ ! -f "$SOURCE_CHAT" ] && [ "$SOURCE_CHAT" = "$FIXTURE" ]; then
  echo "Generating fixture..."
  nvim --headless --noplugin -u NONE \
    --cmd "set rtp^=$PROJECT_ROOT" \
    -l "$SCRIPT_DIR/generate-fixture.lua"
fi
if [ ! -f "$SOURCE_CHAT" ]; then
  echo "ERROR: input file not found: $SOURCE_CHAT"
  exit 1
fi

# ── Discover nvim-treesitter path from host nvim ─────────────────
# The profiling init.lua runs with --clean (no user config), so we
# need to tell it where treesitter lives. We ask the host nvim once
# and pass the path via an environment variable.
TS_PATH="${FLEMMA_PROFILE_TS_PATH:-}"
if [ -z "$TS_PATH" ]; then
  TS_PATH="$(nvim --headless --noplugin \
    -c "lua for _,p in ipairs(vim.api.nvim_get_runtime_file('lua/nvim-treesitter/configs.lua', true)) do io.write(vim.fn.fnamemodify(p, ':h:h:h')); vim.cmd('qa') end; vim.cmd('qa')" \
    2>/dev/null || true)"
fi

if [ -z "$TS_PATH" ]; then
  echo "WARNING: could not find nvim-treesitter. Highlighting may be disabled."
fi

export FLEMMA_PROFILE_TS_PATH="$TS_PATH"

# ── Run metadata ─────────────────────────────────────────────────
RUN_ID="$(date +%Y%m%d-%H%M%S)"
RUN_DIR="$PROJECT_ROOT/.profile/$RUN_ID"

echo "=== Flemma Profile Run: $RUN_ID ==="
echo "Source: $SOURCE_CHAT ($(wc -l <"$SOURCE_CHAT" | tr -d ' ') lines)"
[ -n "$TS_PATH" ] && echo "Treesitter: $TS_PATH"
echo ""

# ── Typing simulation ────────────────────────────────────────────
# Sends one character at a time via tmux with 80-200ms random delays
# to approximate human typing speed.
type_char() {
  local pane="$1" c="$2"
  case "$c" in
    ' ') tmux send-keys -t "$pane" Space ;;
    '-') tmux send-keys -t "$pane" -- '-' ;;
    '(') tmux send-keys -t "$pane" -- '(' ;;
    ')') tmux send-keys -t "$pane" -- ')' ;;
    ';') tmux send-keys -t "$pane" -- '\;' ;;
    *) tmux send-keys -t "$pane" -- "$c" ;;
  esac
  sleep "0.$((RANDOM % 12 + 8))"
}

type_string() {
  local pane="$1" text="$2"
  for ((i = 0; i < ${#text}; i++)); do
    type_char "$pane" "${text:$i:1}"
  done
}

# ── Single profile run ───────────────────────────────────────────
# Launches Neovim in a background tmux window, drives edits through
# three buffer regions (frontmatter, mid-file, end-of-file), then
# collects profiling results.
#
# Args: variant_name extension load_flemma [post_setup_cmd]
run_profile() {
  local name="$1" ext="$2" load_flemma="$3" post_cmd="${4:-}"
  local profile_dir="$RUN_DIR/$name"
  mkdir -p "$profile_dir"

  # Per-run copy — never modify the source file
  local input_file="$profile_dir/input.$ext"
  cp "$SOURCE_CHAT" "$input_file"

  local window_name="prof-$name-$$"
  local flemma_env=""
  if [ "$load_flemma" = "yes" ]; then
    flemma_env="FLEMMA_PROFILE_FLEMMA=1"
  fi

  echo "── $name ──────────────────────────────────"

  # Launch Neovim in a detached tmux window (-d = no focus steal)
  tmux new-window -d -n "$window_name" -P -F '#{pane_id}' \
    "cd $PROJECT_ROOT && FLEMMA_PROFILE_DIR=$profile_dir $flemma_env nvim --clean -u $INIT_LUA $input_file; exec bash" \
    >"$profile_dir/pane_id"

  local pane
  pane="$(cat "$profile_dir/pane_id")"
  local send="tmux send-keys -t $pane"

  wait_flag() {
    local file="$1" timeout="${2:-30}" elapsed=0
    while [ ! -f "$file" ] && [ "$elapsed" -lt "$timeout" ]; do
      sleep 0.3
      elapsed=$((elapsed + 1))
    done
    [ -f "$file" ]
  }

  # Wait for Neovim to fully load and dismiss any "Press ENTER" prompts
  echo -n "  Loading..."
  sleep 4
  $send Enter
  sleep 0.3
  $send Enter
  sleep 0.3
  $send Escape
  sleep 0.5
  echo " ok"

  # Optional post-setup command (for experiment variants)
  if [ -n "$post_cmd" ]; then
    echo -n "  Applying: $post_cmd ..."
    $send ":$post_cmd" Enter
    sleep 0.5
    echo " ok"
  fi

  # Navigate to frontmatter (line 4 — inside the lua codeblock)
  $send ':4' Enter
  sleep 0.5

  # Source the instrumentation (jit.p + :profile + autocmd tracking)
  echo -n "  Instrumenting..."
  $send ":luafile $INSTRUMENT" Enter
  sleep 1
  if ! wait_flag "$profile_dir/ready" 10; then
    echo " FAILED"
    tmux kill-window -t "$pane" 2>/dev/null || true
    return 1
  fi
  echo " ok"

  # ── Phase 1: frontmatter edits (top of file) ──
  echo -n "  Phase 1 (frontmatter)..."
  $send 'A'
  sleep 0.3
  type_string "$pane" " -- profiling"
  $send Enter
  sleep 0.2
  type_string "$pane" "-- second line"
  $send Enter
  sleep 0.2
  type_string "$pane" "-- third line"
  $send Escape
  sleep 0.5
  echo " ok"

  # ── Phase 2: mid-file edits (between tool/thinking folds) ──
  # Edit right after the 17th </thinking> tag — deep in the dense fold
  # region where fold computation is heaviest. Falls back to file midpoint
  # if the file has fewer thinking blocks.
  echo -n "  Phase 2 (mid-file)..."
  local midline
  midline="$(grep -n '</thinking>' "$input_file" | sed -n '17p' | cut -d: -f1)"
  if [ -z "$midline" ]; then
    midline=$(($(wc -l <"$input_file" | tr -d ' ') / 2))
  fi
  $send ":${midline}" Enter
  sleep 0.3
  $send 'o'
  sleep 0.2
  type_string "$pane" "mid-file insertion one"
  $send Enter
  sleep 0.2
  type_string "$pane" "mid-file insertion two"
  $send Escape
  sleep 0.5
  echo " ok"

  # ── Phase 3: end-of-file edits ──
  echo -n "  Phase 3 (end-of-file)..."
  $send 'G'
  sleep 0.3
  $send 'A'
  sleep 0.2
  $send Enter
  sleep 0.1
  type_string "$pane" "appended at end"
  $send Enter
  sleep 0.2
  type_string "$pane" "one more at the end"
  $send Escape
  sleep 0.5
  echo " ok"

  # Let CursorHold fire
  sleep 2

  # Dump profiling results and quit
  echo -n "  Collecting..."
  $send ':FlemmaProfileDump' Enter
  if ! wait_flag "$profile_dir/done" 15; then
    echo " FAILED"
    tmux kill-window -t "$pane" 2>/dev/null || true
    return 1
  fi
  echo " ok"

  sleep 0.5
  tmux kill-window -t "$pane" 2>/dev/null || true
  echo ""
}

# ── Run both passes ──────────────────────────────────────────────
run_profile "baseline-md" "md" "no"
run_profile "chat-flemma" "chat" "yes"

# ── Results ──────────────────────────────────────────────────────
echo "============================================================"
echo "=== COMPARISON ==="
echo "============================================================"
echo ""

printf "%-25s %12s %12s %12s\n" "Variant" "Avg ms/key" "Max ms" "Calls"
printf "%-25s %12s %12s %12s\n" "-------" "----------" "------" "-----"
for v in baseline-md chat-flemma; do
  icp=$(grep 'InsertCharPre' "$RUN_DIR/$v/report.txt" 2>/dev/null || echo "")
  if [ -n "$icp" ]; then
    printf "%-25s %10s ms %10s ms %10s\n" "$v" \
      "$(echo "$icp" | awk '{print $4}')" \
      "$(echo "$icp" | awk '{print $5}')" \
      "$(echo "$icp" | awk '{print $2}')"
  else
    printf "%-25s %12s\n" "$v" "(no data)"
  fi
done

echo ""
echo "Full reports in: $RUN_DIR/"
for v in baseline-md chat-flemma; do
  echo ""
  echo "━━━ $v ━━━"
  cat "$RUN_DIR/$v/report.txt" 2>/dev/null || echo "(missing)"
done
