local parser = require("flemma.parser")

describe("parse_segments", function()
  -- Use parse_inline_content as the public API for parse_segments
  local function parse(text)
    return parser.parse_inline_content(text)
  end

  describe("text only", function()
    it("returns single text segment for plain text", function()
      local segments = parse("hello world")
      assert.equals(1, #segments)
      assert.equals("text", segments[1].kind)
      assert.equals("hello world", segments[1].value)
    end)

    it("returns empty table for empty string", function()
      local segments = parse("")
      assert.equals(0, #segments)
    end)

    it("returns empty table for nil", function()
      local segments = parse(nil)
      assert.equals(0, #segments)
    end)
  end)

  describe("expressions {{ }}", function()
    it("parses single expression", function()
      local segments = parse("hello {{ name }} world")
      assert.equals(3, #segments)
      assert.equals("text", segments[1].kind)
      assert.equals("hello ", segments[1].value)
      assert.equals("expression", segments[2].kind)
      assert.equals(" name ", segments[2].code)
      assert.equals("text", segments[3].kind)
      assert.equals(" world", segments[3].value)
    end)

    it("parses expression at start", function()
      local segments = parse("{{ x }}tail")
      assert.equals(2, #segments)
      assert.equals("expression", segments[1].kind)
      assert.equals("text", segments[2].kind)
    end)

    it("parses expression at end", function()
      local segments = parse("head{{ x }}")
      assert.equals(2, #segments)
      assert.equals("text", segments[1].kind)
      assert.equals("expression", segments[2].kind)
    end)

    it("parses multiple expressions", function()
      local segments = parse("{{ a }} and {{ b }}")
      assert.equals(3, #segments)
      assert.equals("expression", segments[1].kind)
      assert.equals("text", segments[2].kind)
      assert.equals("expression", segments[3].kind)
    end)
  end)

  describe("code blocks {% %}", function()
    it("parses single code block", function()
      local segments = parse("before{% if x then %}after")
      assert.equals(3, #segments)
      assert.equals("text", segments[1].kind)
      assert.equals("before", segments[1].value)
      assert.equals("code", segments[2].kind)
      assert.equals(" if x then ", segments[2].code)
      assert.equals("text", segments[3].kind)
      assert.equals("after", segments[3].value)
    end)

    it("parses code block at start", function()
      local segments = parse("{% x = 1 %}rest")
      assert.equals(2, #segments)
      assert.equals("code", segments[1].kind)
      assert.equals("text", segments[2].kind)
    end)

    it("parses code block at end", function()
      local segments = parse("start{% end %}")
      assert.equals(2, #segments)
      assert.equals("text", segments[1].kind)
      assert.equals("code", segments[2].kind)
    end)

    it("parses mixed expressions and code blocks", function()
      local segments = parse("{% if x then %}{{ name }}{% end %}")
      assert.equals(3, #segments)
      assert.equals("code", segments[1].kind)
      assert.equals(" if x then ", segments[1].code)
      assert.equals("expression", segments[2].kind)
      assert.equals(" name ", segments[2].code)
      assert.equals("code", segments[3].kind)
      assert.equals(" end ", segments[3].code)
    end)
  end)

  describe("trim markers", function()
    it("parses {{- expression }}", function()
      local segments = parse("text {{- name }}")
      assert.equals(2, #segments)
      assert.equals("expression", segments[2].kind)
      assert.is_true(segments[2].trim_before)
      assert.is_nil(segments[2].trim_after)
    end)

    it("parses {{ expression -}}", function()
      local segments = parse("{{ name -}} text")
      assert.equals(2, #segments)
      assert.equals("expression", segments[1].kind)
      assert.is_nil(segments[1].trim_before)
      assert.is_true(segments[1].trim_after)
    end)

    it("parses {{- expression -}}", function()
      local segments = parse("{{- name -}}")
      assert.equals(1, #segments)
      assert.equals("expression", segments[1].kind)
      assert.is_true(segments[1].trim_before)
      assert.is_true(segments[1].trim_after)
    end)

    it("parses {%- code -%}", function()
      local segments = parse("{%- if x -%}")
      assert.equals(1, #segments)
      assert.equals("code", segments[1].kind)
      assert.is_true(segments[1].trim_before)
      assert.is_true(segments[1].trim_after)
    end)

    it("parses {% code -%} (trim after only)", function()
      local segments = parse("{% if x -%}")
      assert.equals(1, #segments)
      assert.equals("code", segments[1].kind)
      assert.is_nil(segments[1].trim_before)
      assert.is_true(segments[1].trim_after)
    end)
  end)

  describe("position tracking", function()
    it("tracks expression position", function()
      local segments = parse("ab{{ x }}cd")
      local expr = segments[2]
      assert.equals("expression", expr.kind)
      assert.is_not_nil(expr.position)
      -- base_line defaults to 0, char_to_line_col(3) -> line=0, col=3
      assert.equals(3, expr.position.start_col)
    end)

    it("tracks code block position", function()
      local segments = parse("ab{% y %}cd")
      local code = segments[2]
      assert.equals("code", code.kind)
      assert.is_not_nil(code.position)
    end)
  end)
end)
