local registry_utils = require("flemma.registry")

describe("flemma.registry", function()
  describe("validate_name()", function()
    it("accepts plain names without error", function()
      assert.has_no.errors(function()
        registry_utils.validate_name("bash", "tool")
      end)
      assert.has_no.errors(function()
        registry_utils.validate_name("my_tool", "tool")
      end)
    end)

    it("accepts urn:flemma: URNs without error", function()
      assert.has_no.errors(function()
        registry_utils.validate_name("urn:flemma:approval:config", "approval resolver")
      end)
    end)

    it("rejects dotted names", function()
      assert.has.errors(function()
        registry_utils.validate_name("my.tool", "tool")
      end)
    end)

    it("includes the registry label in the error message", function()
      local ok, err = pcall(registry_utils.validate_name, "my.tool", "tool")
      assert.is_false(ok)
      assert.matches("tool name 'my.tool' must not contain dots", tostring(err))
    end)

    it("uses the provided label for different registry types", function()
      local ok, err = pcall(registry_utils.validate_name, "my.backend", "sandbox backend")
      assert.is_false(ok)
      assert.matches("sandbox backend name 'my.backend' must not contain dots", tostring(err))
    end)
  end)
end)
