package.loaded["flemma.utilities.truncate"] = nil
local truncate = require("flemma.utilities.truncate")

describe("truncate_line()", function()
  it("returns short lines unchanged", function()
    local result = truncate.truncate_line("hello world", 500)
    assert.equals("hello world", result.text)
    assert.is_false(result.truncated)
  end)

  it("truncates long lines with suffix", function()
    local long = string.rep("x", 600)
    local result = truncate.truncate_line(long, 500)
    assert.is_true(result.truncated)
    assert.truthy(result.text:find("%[truncated%]$"))
    assert.truthy(#result.text <= 500)
  end)

  it("uses default max_chars when not specified", function()
    local long = string.rep("x", 600)
    local result = truncate.truncate_line(long)
    assert.is_true(result.truncated)
    assert.truthy(#result.text <= truncate.MAX_LINE_CHARS)
  end)

  it("handles exact boundary length", function()
    local exact = string.rep("x", 500)
    local result = truncate.truncate_line(exact, 500)
    assert.equals(exact, result.text)
    assert.is_false(result.truncated)
  end)

  it("handles empty string", function()
    local result = truncate.truncate_line("", 500)
    assert.equals("", result.text)
    assert.is_false(result.truncated)
  end)

  it("handles very small max_chars", function()
    local result = truncate.truncate_line("hello world", 5)
    assert.is_true(result.truncated)
    assert.truthy(#result.text > 0)
  end)
end)
